# Generated by Django 4.2.7 on 2023-12-02 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0002_alter_category_options_alter_subcategory_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='slaes_count',
            new_name='sales_count',
        ),
    ]
