# Generated by Django 4.2.7 on 2024-03-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0003_rename_slaes_count_product_sales_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='color_code',
            field=models.CharField(default='#000000', max_length=7),
            preserve_default=False,
        ),
    ]
