# Generated by Django 4.2.7 on 2024-03-09 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0006_maincategory_remove_subcategory_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maincategory',
            options={'verbose_name_plural': 'Main Categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='main_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homeApp.maincategory'),
            preserve_default=False,
        ),
    ]
