# Generated by Django 4.2.7 on 2024-03-09 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0007_alter_maincategory_options_product_main_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeApp.maincategory')),
            ],
            options={
                'verbose_name_plural': 'Subcategories',
            },
        ),
    ]
